[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "reviewnlp"
version = "0.1.0"
description = "NLP product reviews analysis end-to-end project"
requires-python = ">=3.10"
